### ISSUE TITLE
Looks interesting!

### ISSUE THREAD

**Issue by fullofcaffeine** [nweedon/Angular2-Haxe#1]
Hi!

Thanks for this library. I don't use Angular 2 yet, but I'll keep an eye on this one.

When you say: 

> Creating components is pretty much the same as it is in ES6/TypeScript, with a few slight changes due to `limitations` with Haxe metadata.

What limitations specifically? Maybe we could raise the issues up on the Haxe compiler repo in order to improve it/get rid of those limitations?

Cheers.

**Comment by nweedon** [comment]
Hey, thanks for the interest.

The problem mainly lies in what Haxe determines as constant. Take an example direct from the angular.io website, for example:

(TypeScript)

```
@Component({
  selector: 'greet',
  viewInjector: [
    Greeter
  ]
})
@View({
  template: '<needs-greeter></needs-greeter>',
  directives: [NeedsGreeter]
})
class HelloWorld {
}
```

Where 'NeedsGreeter' is a class. As far as I can tell, I've been unable to place a class name directly into Haxe metadata, as such the class name needs to be surrounded in quotes and providing it's fully-qualified package name. The Haxe code would look like this:

```
package example;

class NeedsGreeter
{
}

@Component({
  selector: 'greet',
  viewInjector: [
    Greeter
  ]
})
@View({
  template: `<needs-greeter></needs-greeter>`,
  directives: ["example.NeedsGreeter"]
})
class HelloWorld {
}
```

As you can see, it's a little bit more work, as the string needs to be transformed to the correct class at run-time via `Type.resolveClass` (in AnnotationExtension.hx). This poses an interesting problem:
- The TypeScript annotation and Haxe metadata syntax do not match; matching syntax as closely as possible was one of the original goals of the project.
- However, providing the fully-qualified package and class name makes the metadata (IMO) more maintainable and easier to debug.

As such, I figured this was just a limitation of Haxe and worked around it accordingly. If I'm going in the wrong direction with this or have any suggestions, please let me know! :)

**Comment by kevinresol** [comment]
You can extract the fully qualified type name at compile time using build macros:

Note that I just write `MyType` (no quote, no packages) in the metadata. But inside the build macro i am able to obtain its fully qualified name `"test.MyType"`. Don't forget the import statement `import test.MyType` in Main.hx

``` haxe
// Main.hx
import test.MyType;

@:build(Macro.build())
class Main 
{
    function new()
    {

    }

    static function main() 
    {
        var m = new Main();
        m.test(new MyType());
    }

    @:arg('param1', MyType) // the build macro will add an argument to the function so test() becomes test(param1:MyType)
    function test()
    {

    }
}

// Macro.hx
import haxe.macro.ComplexTypeTools;
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Expr.ComplexType;
import haxe.macro.Expr.Field;
import haxe.macro.TypeTools;

class Macro
{

    macro public static function build():Array<Field> 
    {
        var fields = Context.getBuildFields();

        for (f in fields)
        {
            if (f.name == 'test')
            {
                var meta = f.meta[0];
                var argName = exprToString(meta.params[0]);
                var argType = composeType(exprToString(meta.params[1]));

                // you probably need this
                var fullyQualifiedTypeName = TypeTools.toString(ComplexTypeTools.toType(argType)); 
                trace(fullyQualifiedTypeName); // 'test.MyType'

                switch (f.kind) 
                {
                    case FFun(func):
                        // modify the argument list
                        func.args = [{
                            name:argName,
                            type:argType,
                        }];

                    default:

                }
            }
        }

        return fields;
    }

    private static function exprToString(e:Expr):String
    {
        return switch (e.expr) 
        {
            case EConst(CString(s)): s;
            case EConst(CIdent(s)): s;
            default: throw "unsupported";
        }
    }

    private static function composeType(path:String):ComplexType
    {
        var a = path.split(".");
        var className = a.pop();
        return TPath( { name:className, pack:a } );
    }
}

// test/MyType.hx
class MyType
{

    public function new() 
    {

    }

}
```

**Comment by nweedon** [comment]
Hi @kevinresol, thanks for the input. My original approach was similar to this, however, TPath doesn't seem to resolve to the correct JavaScript class/function at run-time, as such I've opted for another approach (see BuildPlugin.hx). It seems a little hacky to me at the moment, so if you can recommend another way of going about it so that classes resolve without using `Type.resolveClass`, that would be greatly appreciated.
