### ISSUE TITLE
awesome-angular2

### ISSUE THREAD

**Issue by PatrickJS** [nweedon/Angular2-Haxe#8]
I'm adding this and you to the repo. Please update the list if you create more angular 2 haxe resources

**Comment by PatrickJS** [comment]
done via https://github.com/angular-class/awesome-angular2/commit/91b3f85e70b309f53a44f85e77b0f049990955b7

feel free to close the issue

**Comment by nweedon** [comment]
Great, thanks for letting me know @gdi2290. :)

**Comment by PatrickJS** [comment]
thanks for making the project! I added you to the awesome-angular2 repo so you can update any links. If you need suggestions or feedback I can connect you with someone from the Angular Team
